const express=require('express');const {z}=require('zod');const {models}=require('../db');const {validate}=require('../middleware/validate');const {requireRole}=require('../middleware/auth');const {AppError}=require('../errors');const matches=require('../services/matches');const attacks=require('../services/attacks');const submissions=require('../services/submissions');const {recordProgress}=require('../services/participantProgress');const {emitMatch}=require('../realtime');
const params=z.object({id:z.string().uuid()});const attackSchema=z.object({type:z.enum(['CONDITION_CHANGE','OPERATOR_CHANGE','BOUNDARY_ATTACK','EDGE_CASE_ATTACK']),line:z.number().int().positive().optional()});const codeSchema=z.object({sourceCode:z.string().max(50000),language:z.enum(['cpp','python','java'])});const problemAssignmentSchema=z.object({problemId:z.string().uuid().nullable()});const endSchema=z.object({winnerTeamId:z.string().uuid().nullable().optional(),reason:z.string().max(120).optional()});
function makeRouter(io){const router=express.Router();router.get('/',async(req,res,next)=>{try{if(req.user.role==='admin'){const tournament=await models.Tournament.findOne({status:{$in:['setup','active']}}).sort({createdAt:1}).select('_id').lean();const all=await models.Match.find(tournament?{tournament_id:tournament._id}:{}).sort({match_number:1}).lean();const rows=await Promise.all(all.map(async m=>({id:m._id,match_number:m.match_number,state:m.state,started_at:m.started_at,ends_at:m.ends_at,winner_team_id:m.winner_team_id,problem_id:m.problem_id,problem_title:(await models.Problem.findById(m.problem_id).select('title').lean())?.title,team_a:(await models.Team.findById(m.participants.find(p=>p.role==='CODER')?.team_id).select('name').lean())?.name,team_b:(await models.Team.findById(m.participants.find(p=>p.role==='DETECTIVE')?.team_id).select('name').lean())?.name})));return res.json({matches:rows})}res.json({matches:await matches.getMyMatches(req.user)})}catch(e){next(e)}});
router.get('/:id',validate(params,'params'),async(req,res,next)=>{try{const match=await matches.getMatch(req.user,req.params.id,req.user.role==='admin');const problem=await models.Problem.findById(match.problem_id).lean();const team=await require('../services/identity').getTeamForUser(req.user.id);const tournament=await models.Tournament.findById(match.tournament_id).lean();const history=await attacks.getAttackHistory(req.params.id,req.user.role==='admin');res.json({match,publicTests:(problem?.test_cases||[]).filter(x=>!x.is_hidden).map(({_id,input_text,expected_output})=>({id:_id,input_text,expected_output})),attackHistory:history,attackBudget:team?Number(tournament?.config?.attacksPerDetective??3):null})}catch(e){next(e)}});
router.post('/:id/start',validate(params,'params'),requireRole('admin'),async(req,res,next)=>{try{const match=await matches.startMatch(req.user,req.params.id);emitMatch(io,req.params.id,'match:started',{matchId:req.params.id,state:match.state,endsAt:match.ends_at});res.json({match})}catch(e){next(e)}});
router.patch('/:id/problem',validate(params,'params'),validate(problemAssignmentSchema),requireRole('admin'),async(req,res,next)=>{try{const match=await models.Match.findById(req.params.id);if(!match)throw new AppError(404,'Match not found.');if(!['READY','WAITING'].includes(match.state))throw new AppError(409,'Challenges can only be changed before a match starts.');if(req.body.problemId){const problem=await models.Problem.findOne({_id:req.body.problemId,is_active:true}).lean();if(!problem)throw new AppError(404,'Active challenge not found.');match.problem_id=problem._id;match.code.source_code=problem.starter_code?.[match.code.language]||''}else{match.problem_id=null;match.code.source_code=''}match.version++;await match.save();await require('../services/audit').audit(req.user.id,'match.problem_assigned','match',match._id,{problemId:req.body.problemId});res.json({match:{id:match._id,problem_id:match.problem_id}})}catch(e){next(e)}});
router.post('/:id/pause',validate(params,'params'),requireRole('admin'),async(req,res,next)=>{try{const match=await matches.pauseMatch(req.user,req.params.id);emitMatch(io,req.params.id,'match:paused',{matchId:req.params.id,remainingSeconds:match.remaining_seconds});res.json({match})}catch(e){next(e)}});
router.post('/:id/end',validate(params,'params'),validate(endSchema),requireRole('admin'),async(req,res,next)=>{try{const body=req.body;const match=await matches.endMatch(req.user,req.params.id,body.winnerTeamId||null,body.reason||'admin_override');emitMatch(io,req.params.id,'match:completed',{matchId:req.params.id,winnerTeamId:match.winner_team_id,result:match.result});res.json({match})}catch(e){next(e)}});
router.put('/:id/code',validate(params,'params'),validate(codeSchema),async(req,res,next)=>{try{const data=await matches.syncCode(req.user,req.params.id,req.body.sourceCode,req.body.language);emitMatch(io,req.params.id,'code:changed',{matchId:req.params.id,sourceCode:req.body.sourceCode,language:req.body.language,revision:data.revision});res.json(data)}catch(e){next(e)}});
router.post('/:id/run',validate(params,'params'),validate(codeSchema),async(req,res,next)=>{try{const result=await submissions.runPublic(req.user,req.params.id,req.body.sourceCode,req.body.language);await recordProgress(req.user.id,req.params.id,{type:'public_run',sourceCode:req.body.sourceCode,language:req.body.language,passedTests:result.passed,detail:{status:result.status,passed:result.passed,total:result.total}});emitMatch(io,req.params.id,'test:result',{matchId:req.params.id,scope:'public',result});res.json(result)}catch(e){next(e)}});
router.post('/:id/submit',validate(params,'params'),validate(codeSchema),async(req,res,next)=>{try{let result;try{result=await submissions.submit(req.user,req.params.id,req.body)}catch(error){await recordProgress(req.user.id,req.params.id,{type:'submission_error',sourceCode:req.body.sourceCode,language:req.body.language,detail:{status:'error'}});throw error}await recordProgress(req.user.id,req.params.id,{type:'submission',sourceCode:req.body.sourceCode,language:req.body.language,passedTests:result.passed,detail:{status:result.status,passed:result.passed,total:result.total}});emitMatch(io,req.params.id,'submission:received',{matchId:req.params.id,status:result.status,passed:result.passed,total:result.total});if(result.status==='accepted')emitMatch(io,req.params.id,'match:completed',{matchId:req.params.id,reason:'accepted_submission'});res.json(result)}catch(e){next(e)}});
router.post('/:id/attacks',validate(params,'params'),validate(attackSchema),async(req,res,next)=>{try{const result=await attacks.applyAttack(req.user,req.params.id,req.body);await recordProgress(req.user.id,req.params.id,{type:'attack',detail:{attackType:result.attack.attack_type,result:result.attack.result,severity:result.attack.severity}});const attack={id:result.attack.id,type:result.attack.attack_type,result:result.attack.result,severity:result.attack.severity,createdAt:result.attack.created_at};emitMatch(io,req.params.id,'attack:applied',{matchId:req.params.id,attack,sourceCode:result.code});res.json({attack,remaining:result.remaining})}catch(e){next(e)}});
router.get('/:id/attacks',validate(params,'params'),async(req,res,next)=>{try{await matches.getMatch(req.user,req.params.id,req.user.role==='admin');res.json({attacks:await attacks.getAttackHistory(req.params.id,req.user.role==='admin')})}catch(e){next(e)}});
return router}
module.exports=makeRouter;
